### ISSUE TITLE
Document sprint Henrietta Lacks in wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#107]
https://github.com/18F/clinical-trials/wiki/Sprint-Henrietta-Lacks:-June-5-to-June-16,-2017

**Comment by jamiealbrecht** [comment]
I've taken a look. 👍 👍  from me. @jkoufopoulos, did you have a chance to take a look? If so, we can move this to done. :)

**Comment by jkoufopoulos** [comment]
@jamiealbrecht I just read through. Kudos to @MelissaBraxton. Happy to move done. @acolter may wish to take a peek too!
