### ISSUE TITLE
Make updates to prototypes based off of interviews

### ISSUE THREAD

**Issue by maya** [18F/clinical-trials#116]
What updates do we want to make? @austinhernandez @MelissaBraxton

**Comment by austinhernandez** [comment]
Hey Maya, here are some mocks based on solutions to the High confidence 

Copied from Google Docs:



## User need: to know what is included in search results to be sure nothing is missed
* Synonyms sentence “Including results for shell-shock, post traumatic stress disorder, and delayed-stress disorder.” 
* Feasibility question: can we differentiate spelling errors from different words? what does this look like with 30 results returned?
 * Can we show the most popular of the words for prioritization?

#### Related terms idea 1:
![relatedv1](https://user-images.githubusercontent.com/23194720/27502281-9aac9aa4-5838-11e7-85c6-49afa0b03903.png)

this is a super low-fi way to add a pop-out of other related terms. it could use some wordsmithing.

#### Related terms idea 2:
![related_terms](https://user-images.githubusercontent.com/23194720/27502215-35e97074-5838-11e7-892a-ca266720e61e.png)

this is a different approach to add the related terms closer to the results and not overwhelm the user with the amount of "related words" also includes ability to remove. it also cold use a content look thru.

## User need: to know what studies are new or changed
* “New” label
* Feasibility question: What time frame can we set on these (e.g. first opened / not spelling changes)? How might we recognize a record that’s been recently updated in a small way (a single letter) versus, a new record being created, or major change?

![newlabel](https://user-images.githubusercontent.com/23194720/27502498-116a545a-583a-11e7-9272-49dffa10f2e7.png)

this is a concept to show how you could add a tool tip to show what makes a study record "new"

**Comment by maya** [comment]
Tooltips are in https://github.com/18F/clinical-trials/issues/120 and "Related terms idea 2" is awaiting feedback from the CT dev team.
