### ISSUE TITLE
Reduce size of search component on results page

### ISSUE THREAD

**Issue by austinhernandez** [18F/clinical-trials#118]
https://federalist-proxy.app.cloud.gov/preview/18f/clinical-trials/beta/search-results/?cond=&term=&cntry1=&state1=&SearchRecruiting=Find+a+study+to+participate+in&recrs=

Acceptance criteria
- [x]  Attaching a design for the search component for the results page
- [ ]  Review with dev team

**Comment by austinhernandez** [comment]
Concept 1 single line:
![3](https://user-images.githubusercontent.com/23194720/27643857-3cdcf5a2-5bf0-11e7-9e0e-9e7d95e0a1ae.png)

Concept 2: Country and state (conditional field are in expanded view)
![1](https://user-images.githubusercontent.com/23194720/27643763-f2f14af6-5bef-11e7-80ae-c0d2f5524f8f.png)

**Comment by austinhernandez** [comment]
Question from Justin on July 7 - Unclear to me though if there are things like @austinhernandez reduced search form on the results page is ready. Reply from @maya I think that was done before our new approach of not working on their old designs, so I do not know whether or not to move forward with it.

So I'm putting it in blocked for right now until it is ready to be implemented or shown to the dev team.

**Comment by maya** [comment]
Done in https://federalist-proxy.app.cloud.gov/preview/18f/clinical-trials/new-design/search-results/.
