### ISSUE TITLE
Improve radio button content

### ISSUE THREAD

**Issue by maya** [18F/clinical-trials#119]
People had issues understanding the "closed" button. More detail in research notes.

**Comment by MelissaBraxton** [comment]
Drafted some options [here](https://docs.google.com/document/d/1ttsDhGDZ-riv2J-cw0U-08LVe27XdvPjyL6JVhLipcw/edit).

**Comment by maya** [comment]
@MelissaBraxton which option would you like to use?

**Comment by austinhernandez** [comment]
finalized radio button content here: https://gsa.invisionapp.com/share/Z3CGG92C7#/242287737_Homepage_radio_buttons
