### ISSUE TITLE
Read client provided research material

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#12]
- [x] Read material
- [x] Synthesize and write up learnings

**Comment by acolter** [comment]
https://drive.google.com/drive/u/1/folders/0B8dk4rmN4KrvWUFwSlAyR1JlV1U

**Comment by MelissaBraxton** [comment]
[Sheet where we can log our thoughts](https://docs.google.com/spreadsheets/d/1a63BW8RWLv6X6aIMPbNHs3CPE-rtPW0DIEZO3TOl6Nk/edit#gid=1710960007)

**Comment by acolter** [comment]
Closing all issues from Phase 1
