### ISSUE TITLE
Add tooltip to "New" label

### ISSUE THREAD

**Issue by maya** [18F/clinical-trials#120]
Add a tooltip to the "New" label so that people can understand the timeframe the new trial was posted.

Timeframe: one month from opening

## Tentative design
![](https://user-images.githubusercontent.com/23194720/27502498-116a545a-583a-11e7-9272-49dffa10f2e7.png)

## Acceptance criteria
- [x] Content is written and reviewed @jamiealbrecht 
- [x] Design is created or approved @austinhernandez 
- [x] Tooltips are developed and accessible @maya

**Comment by maya** [comment]
Thinking about this content: `Study opened within the last 30 days`.

@austinhernandez asked should it be “posted” “opened” or “updated.”

@jamiealbrecht what do you think about this content?

People in testing understood this as from first being opened so i don't think "updated" works.

**Comment by jamiealbrecht** [comment]
I think "posted" is most accurate. I believe some studies can technically "open" before they get to ct.gov.
