### ISSUE TITLE
Revise project brief

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#15]

**Comment by acolter** [comment]
This is the original project brief that was shown at the kickoff meeting: 

ClinicalTrials.gov provides access to information about clinical studies (such as enrolling in one or learning the outcome) as well as a way for organizations to register clinical studies and report their results. 

There is a gap between what information ClinicalTrials.gov offers, what users — particularly patients and their caregivers — expect it to offer, and how easy it is for them to get it. 

This project aims to characterize that gap by identifying user needs, expectations, and barriers in the beta site, then make recommendations to address them.

**Comment by acolter** [comment]
Here's the revision I'm sending to Betsy: 

ClinicalTrials.gov provides the public access to information on publicly and privately supported clinical studies on a wide range of diseases and conditions.

There is a gap between the information ClinicalTrials.gov offers and what users expect it to offer.

This project aims to characterize that gap by identifying user needs and expectations. We will recommend ways to make it easier for users to understand ClinicalTrials.gov’s mandate, the information the beta site provides, and what kinds of tasks and decisions this information is designed to support.

**Comment by acolter** [comment]
Here is the revision Betsy sent. Let's call this final. 

ClinicalTrials.gov provides the public access to information on publicly and privately supported clinical studies on a wide range of diseases and conditions. **The information is submitted by those conducting the clinical studies and is put to a variety of uses.**

There may be gaps between the information, **search capabilities, and usability features** that ClinicalTrials.gov offers and what **different user groups** expect it to offer.

This project aims to characterize that gap by identifying **common and divergent** needs and expectations **across user groups**. We will recommend ways to make it easier for users to understand ClinicalTrials.gov’s mandate, the information **and search capabilities** the beta site provides, and what kinds of tasks and decisions this information is designed to support.
