### ISSUE TITLE
Get analytics from the beta site

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#20]

**Comment by acolter** [comment]
Eric needs to get clearance to share docs with us.

**Comment by austinhernandez** [comment]
Tao provided us with analytics data.

The date range is from Feb 26 – Mar 4 and the file contains sheets for:
- Geo_org breakdown for all CTGOV render
- Geo_org breakdown for search with “undefined” term, which triggers the return of all trials and are more likely API users
- Searchtext terms
- Browser desktop breakdown
- Browser mobile breakdown (with summary stat inserted as a smaller table)
- Note: "The session count represents approximate number of unique users, and IP are the unique IP count."

Document on our drive under client-supplied docs and here: [CT.gov Feb 26 – Mar 4 analytics data](https://docs.google.com/a/gsa.gov/spreadsheets/d/1zYAkMJOdieHYrSckrWOeb78m15r8dtXhwTOaUcuAK8I/edit?usp=sharing)

**Comment by acolter** [comment]
Closing all issues from Phase 1
