### ISSUE TITLE
Analyze beta site analytics for opportunities

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#21]

**Comment by acolter** [comment]
Dependent on https://github.com/18F/clinical-trials/issues/20

**Comment by acolter** [comment]
- Pages with the highest read time
- Search terms
- Monthly / daily users
- Most popular pages
- Referral pages

**Comment by austinhernandez** [comment]
@MelissaBraxton this is what I was thinking in terms of an action plan for the analytics. It's a work in progress, but feel free to change this and add to it.

Additional information in #20 

Mobile and desktop users:
<img width="361" alt="screen shot 2017-03-24 at 4 38 01 pm" src="https://cloud.githubusercontent.com/assets/23194720/24312763/6d895942-10b0-11e7-93a3-999308624021.png">

Desktop users:
<img width="245" alt="screen shot 2017-03-24 at 4 33 53 pm" src="https://cloud.githubusercontent.com/assets/23194720/24312565/8e892fce-10af-11e7-902c-0327e19c43a4.png">

## What this information tells me: 
- There's a whopping 3,043,220 users a users a week to the site.
- 2,600,329 a majority (85%) are coming from the desktop site, the rest from mobile
- Most users come from Chrome on a Windows 

## Why does that matter?
- Analytics won't tell you everything you need to know, its just a piece of a puzzle
- But, with such a sizable pool of users so much cool stuff can be done to experiment and test
- It's important for stakeholders to understand the traffic of the site so you can prioritize issues and requests 
  - "Is this an issue that effects 80% of users or 2%?
- You can make assumptions on the users based on their browser and OS

## How can I make this actionable:
- Yes the site needs to work for everyone, but when launching small features at a time you want to start with the highest represented group. 
- You might want to look at finding more granular information like "What pages are they looking at?"

## Goal setting
- The most important thing about quantitative data is creating a hypothesis that can be measured
  - "We believe if we do X then Y will happen"
- An easy goal is "We want to reduce the amount of calls to our customer service team to ask for customer service number" or "We want to reduce the number of 'no results' search results!"
- Next set a game plan, "We believe that if we add a contact section at the top of the form, we can achieve that." or "We believe the language is unclear on the search box about what you can search for."
- Set up multi-variant (A/B tests) and see if there are any changes 
- A good resource on tracking the user journey - https://mixpanel.com/funnels/

**Comment by austinhernandez** [comment]
Note to self and @MelissaBraxton for working session Wednesday: A little birdie told me that @onezerojeremy did something similar to this for FEC.

**Comment by MelissaBraxton** [comment]
Awesome. And I am just now reading through your first take above. Great
start!  Thanks so much for getting the ball rolling. Looking forward to
digging in a bit more on Wednesday!

Melissa Braxton, MS
User Experience Designer, 18F
PhD Candidate, Human Centered Design & Engineering
University of Washington, College of Engineering
Cell: (415) 696-4216
https://18f.gsa.gov/

**Comment by onezerojeremy** [comment]
Oh cool! 15% mobile is pretty substantial! 

Do we have access to the search logs?

**Comment by austinhernandez** [comment]
@onezerojeremy yes! the file they sent is here: [CT.gov Feb 26 – Mar 4 analytics data](https://docs.google.com/a/gsa.gov/spreadsheets/d/1zYAkMJOdieHYrSckrWOeb78m15r8dtXhwTOaUcuAK8I/edit?usp=sharing)

**Comment by austinhernandez** [comment]
Just looking at some of the search data:

**137,516 total search results
new learning from team: undefined or empty searches are probably API calls**

- 102,690: undefined or empty searches- 75% 
  - (result returns: **240,252 studies found for: ALL**)
- 23,552: searches for NCT########## - Approx 17%
- 1,400: terms that are long and specific e.g. "a twelve-week, double-blind, placebo-controlled, randomized, parallel-group, multicenter study of the safety and efficacy of jzp-110" or "efficacy, safety and tolerability of avp-786 (deuterated [d6]-dextromethorphan hydrobromide [d6-dm]/quinidine sulfate [q]) for the treatment of agitation in patients with dementia of the alzheimer"
- 270: 5 digit numbers (zip code?)
- 2,000: 6, 7, 8, or 9 digit number (what could these be?)

## top 10 searches:
139	nivolumab
117	pembrolizumab
108	atezolizumab
103	sleep
82	avelumab
78	diabetes
73	durvalumab
71	depression
63	kte-c19
63	multiple sclerosis

**Comment by acolter** [comment]
Closing all issues from Phase 1
