### ISSUE TITLE
Investigate USWDS for rapid prototyping

### ISSUE THREAD

**Issue by austinhernandez** [18F/clinical-trials#22]

**Comment by austinhernandez** [comment]
Spoke to @juliaelman about help using the USWDS for prototyping! 

Recap:
- She's more than happy to help! 
- She'd prefer if I worked in Sketch and then she coded my mockups
  - she's fast 
  - she can co-work and help me with code 

concerns / confirms: 
- Confirm: 72 hours of billable work for USWDS
- Concern: Would the client would feel OK with using USWDS?
  - As long as we let the client know recreating their site and branding would take longer to prototype
  - As long as the expectation is that they can keep their branding
- Confirm: Expected deliverables 
  - Would a USWDS prototype be a good deliverable?

**Comment by juliaelman** [comment]
Feel free to pull me into any discussions you might think would be helpful too! Happy to help in whatever way I can.
