### ISSUE TITLE
Comparative analysis 

### ISSUE THREAD

**Issue by austinhernandez** [18F/clinical-trials#33]
This is a mural board I've been using to identify patterns for data heavy sites (library, resource, and cancer information sites) 

https://app.mural.ly/t/gsa6/m/gsa6/1488404833003

**Comment by austinhernandez** [comment]
Here's a list of organizations using CT.gov API:

- emmes.com
- mayo.edu
- who.int
- nih.gov
- nlm.nih.gov
- rksystems.com
- med.stanford.edu
- mulhauser.net
- oicr.on.ca
- thomson.com
- partnershipagainstcancer.ca
- duke.edu
- semanticbits.com
- optum.com
- Lewin.com
- deloitte.com
- xogene.com
- secassociates.com
- leeterwal.com
- aucklandnz.com
- icfi.com
- lilly.com
- sylogent.com
- trialscopeinc.com
- virtify.com
- mayo.edu
- trialreach.com
- partnershipagainstcancer.ca
- larvol.com
- lmpolicyresearch.com
- truvenhealth.com
- n-of-one.com
- arcadia.spb.ru
- find-inc.com
- compositeapps.net
-

**Comment by acolter** [comment]
Closing all issues from Phase 1
