### ISSUE TITLE
Prototype new study detail page

### ISSUE THREAD

**Issue by nicoleslaw** [18F/clinical-trials#42]
Related to #37 

Making a note that we're working on this. Working copy is here: https://docs.google.com/document/d/1aUEyNXF_R61I0TlmrcyqWY_FSZj9f2SjUxC-i44wd-8/edit#

Feel free to accept changes that work for you @austinhernandez as you incorporate them. I only used suggest there so you can see what I changed.

**Comment by acolter** [comment]
Closing all issues from Phase 1
