### ISSUE TITLE
Prototype a page with an interactive glossary term

### ISSUE THREAD

**Issue by nicoleslaw** [18F/clinical-trials#43]
Just an idea...

Consider incorporating the existing [Glossary](https://clinicaltrials.gov/beta/about-studies/glossary) into the page in a more interactive way in a test with the [18F Glossary Tool](https://github.com/18F/glossary).

We used this with USWDS styling for FBI and it was really helpful (and tested well!)—we could potentially reuse styles from Aviva.

**Comment by acolter** [comment]
Closing all issues from Phase 1
