### ISSUE TITLE
Create content survey for NLM

### ISSUE THREAD

**Issue by acolter** [18F/clinical-trials#55]

**Comment by nicoleslaw** [comment]
Ideas for questions:

- What are the top 3 things you want patients and laypeople to know about the site?

- If you were describing ClinicalTrials.gov to a family member, what would you say about it?

[Or similarly...]
- If a patient was telling a friend about the site, what would you want them to say?

- If ClinicalTrials.gov was a person, how would you describe them? How does that differ from the overarching NLM or NIH brand or writing style?

**Comment by nicoleslaw** [comment]
@austinhernandez Do you have any other branding or messaging-related questions that might be good to include? (We can talk through in our pairing time.)

**Comment by nicoleslaw** [comment]
Drafting this here: https://docs.google.com/a/gsa.gov/forms/d/1g5L49ppcWSN8nuJtS4e_0BbNN060Gu_hNz5FYe3ZbKU/edit

**Comment by nicoleslaw** [comment]
Closing as I've updated the survey and shared the announcement email draft with Angela via Slack.
