### ISSUE TITLE
Review and incorporate CT.gov team's feedback from working session

### ISSUE THREAD

**Issue by austinhernandez** [18F/clinical-trials#57]
Took notes from NIH/NLM teams directly on the mockup: https://projects.invisionapp.com/d/main#/projects/prototypes/10546277/comments

Additional notes:
- 50% of traffic comes directly to the study record details page.
- they use “intervention” instead of “treatment” because the procedure/device/method doesn’t _necessarily_ treat. it may *potentially treat* 
- they had the option to enforce plain language for people submitting trials, but they said no because they we afraid the drug companies uploading text would turn CT.gov into free advertisement (e.g. This is a groundbreaking treatment brought to you by the talented makers of the popular drug x!")

**Comment by acolter** [comment]
Closing all issues from Phase 1
