### ISSUE TITLE
Design final report/presentation 

### ISSUE THREAD

**Issue by austinhernandez** [18F/clinical-trials#59]
Using FBI's framework as a starting point - https://drive.google.com/open?id=1z1o1tUAeMvRLTB0O9PnucgAxa_JzVyvcOZW_VLokyTk

**Comment by austinhernandez** [comment]
[OGP Research Report_Final_9.25.15.pdf](https://github.com/18F/clinical-trials/files/869047/OGP.Research.Report_Final_9.25.15.pdf)
[Pre-read_Phase 2 User needs and flows.pdf](https://github.com/18F/clinical-trials/files/869048/Pre-read_Phase.2.User.needs.and.flows.pdf)

**Comment by acolter** [comment]
Closing all issues from Phase 1
