### ISSUE TITLE
Design the mockup piece of final report

### ISSUE THREAD

**Issue by austinhernandez** [18F/clinical-trials#61]
Show the client the "solutions" and "recommendations" we came up with and turning user feedback into action. 

- [ ] Implement @nicoleslaw's content changes
- [ ] List our observations/findings
- [ ] Show CT's prioritization of tasks
- [ ] Show how my designs seek to solve those issues
- [ ] Show user feedback on my prototypes
- [ ] Show what the process would look like going forward

**Comment by acolter** [comment]
Closing all issues from Phase 1
