### ISSUE TITLE
Finalize Invision prototype with 18F content and minor feedback changes

### ISSUE THREAD

**Issue by austinhernandez** [18F/clinical-trials#62]
# [Final version here](https://projects.invisionapp.com/share/R9AVPDEU2#/screens/225847409_F-Homepage)
- implemented @nicoleslaw's feedback
- added closed and opened filter screens
- added search results for "all" and "only recruiting"

**Comment by austinhernandez** [comment]
Source files are here for @onezerojeremy whenever you're ready to make changes -  [clinicaltrials_prototype-3-28-ah.sketch](https://drive.google.com/open?id=0B0ppzHnivtsDRDdjVjNBS29XdDA)

**Comment by acolter** [comment]
Closing all issues from Phase 1
