### ISSUE TITLE
Identify metrics

### ISSUE THREAD

**Issue by acolter** [18F/clinical-trials#64]
Create a set of qualitative and quantitative metrics that the site can use to determine whether it's working successfully. 

Justin started a doc at https://docs.google.com/document/d/1pgEOgA6NOXmND2gMndSkvGNCj4ZIhp1kUeVDavE1c6U/edit#

**Comment by jkoufopoulos** [comment]
Teardown of Foresee and brainstormed new approach. https://docs.google.com/spreadsheets/d/1nGCXTJQomW4ua2YXwm0tUdtcSH1BYlLEdbUiIiQAV0c/edit#gid=590386030

**Comment by jkoufopoulos** [comment]
@acolter took another shot at our metrics doc folding back in our current thinking. @MelissaBraxton would love your thoughts and ideas.

**Comment by jkoufopoulos** [comment]
- [x] Create a set of qualitative and quantitative metrics ClinicalTrials.gov could use to measure performance
- [x] Collect feedback from Angela and Melissa
