### ISSUE TITLE
Apply the USWDS to the study detail page

### ISSUE THREAD

**Issue by acolter** [18F/clinical-trials#79]

**Comment by MelissaBraxton** [comment]
@maya and @austinhernandez  - Can we move this to done? (We have separate cards for the gov approved tag and dealing with weird data.)

**Comment by maya** [comment]
We have a prototype created from scratch, but this is not applied to their current site.

**Comment by MelissaBraxton** [comment]
Ah, I misunderstood the meaning of the card to be about prototyping this, not actual implementation. So we should leave it as is?  (I thought NLM would be the ones doing this work.)

**Comment by maya** [comment]
I don't know that this is decided. We talked about me phasing it in with their current site at one point.
