### ISSUE TITLE
schedule debrief w/ Deborah re: usability test plan

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#86]

**Comment by jkoufopoulos** [comment]
@MelissaBraxton can you give me ideally 1 week advance notice for when we test our new designs with a researcher or journal editor?

**Comment by MelissaBraxton** [comment]
Based on comments in yesterday's check in, wondering  if this is still a priority?

**Comment by jkoufopoulos** [comment]
I think Becky's comments were pretty clear: no. I think that the problem that this tries to solve is around buy-in. And I think we get buy-in by having evidence, and evidence from folks like the systematic reviewer that we had yesterday that our changes aren't impeding their experience. Do you agree @acolter ?

**Comment by acolter** [comment]
I think we definitely run our test plan by Becky. Can suggest to her that she run it by Deb (if that's the question)

**Comment by jkoufopoulos** [comment]
@acolter I actually think the title of this issue may not be right. The idea was to schedule a user interview with Deborah as an observer to secure her buy-in. And I think we heard from Becky that this wasn't a priority or likely to move her. Closing the issue.
