### ISSUE TITLE
Develop content testing research protocol

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#92]

**Comment by jamiealbrecht** [comment]
Content testing protocol for homepage and disclaimer : https://docs.google.com/document/d/1uC7U-c6w-_h9mM6ZW2geKUg7iug39TTrEs0aW_OQlZQ/edit

**Comment by MelissaBraxton** [comment]
@jamiealbrecht - Update to include questions around new homepage design.
