### ISSUE TITLE
Highlight synonyms in "search results" page prototype

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/clinical-trials#99]

**Comment by maya** [comment]
Prototype 😎: https://federalist-proxy.app.cloud.gov/preview/18f/clinical-trials/beta/search-results/

**Comment by maya** [comment]
@MelissaBraxton @jkoufopoulos I've highlighted `Post Traumatic Stress Disorder` in the search results page (posted above). Let me know if this is what you were going after.

**Comment by maya** [comment]
@jkoufopoulos what do you think of this prototype for highlighting synonyms on the "search results" page? https://federalist-proxy.app.cloud.gov/preview/18f/clinical-trials/beta/search-results/ (Test comment)

**Comment by MelissaBraxton** [comment]
LGTM!
